sudo: required
services:
     - docker

before_install:
     - docker build -t shiwani/docker-react -f Dockerfil.dev .

scripts:
     - docker run shiwani/docker-react npm run test -- --coverage 

   